rename electrum to electrumfairchains remove nonfree-system-builds

diff --git a/contrib/make_tgz b/contrib/make_tgz
--- a/contrib/make_tgz
+++ b/contrib/make_tgz
@@ -5,12 +5,6 @@ set -e
 CONTRIB="$(dirname "$(readlink -e "$0")")"
 ROOT_FOLDER="$CONTRIB"/..
 PACKAGES="$ROOT_FOLDER"/packages/
-LOCALE="$ROOT_FOLDER"/electrum/locale/
-
-if [ ! -d "$LOCALE" ]; then
-  echo "Run make_locale first!"
-  exit 1
-fi
 
 if [ ! -d "$PACKAGES" ]; then
   echo "Run make_packages first!"
@@ -25,7 +19,7 @@ fi
     echo "<<<"
 
     # we could build the kivy atlas potentially?
-    #(cd electrum/gui/kivy/; make theming) || echo "building kivy atlas failed! skipping."
+    #(cd electrumfairchains/gui/kivy/; make theming) || echo "building kivy atlas failed! skipping."
 
     python3 setup.py --quiet sdist --format=zip,gztar
 )
